### ISSUE TITLE
md-row-select parsing issue when defined by ng-attr-x

### ISSUE THREAD

**Issue by Fardinak** [daniel-nagy/md-data-table#64] opened 2015-07-31 21:38 UTC
I have the same need as #63; and now that I think of it, I'd face the same problem in the next step, but first:
I chose the `ng-attr-x` way to handle the adding/deleting the attribute like this:
```html
<table md-data-table
    ng-attr-md-row-select="{{ session.isAuthorized('core.delete_structure') ? 'selectedItems' : undefined }}">
```
This should result in:
```html
<table md-data-table
    md-row-select="selectedItems">
```
if the user has the respective permission and to the following if not:
```html
<table md-data-table>
```

Instead it throws a Syntax error regarding the angular expression provided. This works as expected on any other imagined attribute though (e.g. `ng-attr-md-row`). Any idea where that's coming from?

**Comment by daniel-nagy** [comment] 2015-08-01 00:11
`ng-attr-md-row-select` will not work at the moment. I'll need to make some modifications.

**Comment by daniel-nagy** [comment] 2015-08-09 18:15
dupe of issue #63

**Closed by daniel-nagy** 2015-08-09 18:15 UTC
