### ISSUE TITLE
Page Number disappears after going through 10 pages

### ISSUE THREAD

**Issue by Praetorss** [daniel-nagy/md-data-table#372] opened 2016-04-18 16:07 UTC
Steps to replicate:

1. Load a grid that contains more than 10 pages
2. Using page navigation buttons browse to page number 10. Page number is displayed all the way through
3. Using page navigation buttons browse to page number 11. Page number disappears.

The same can be replicated if user selects a page. For e.g. page 30 and then navigates through 11 pages in direction forward.

Found this on 0.10.4 and replicated on 0.10.5

**Comment by daniel-nagy** [comment] 2016-04-18 16:17
Dupe of #358.

**Closed by daniel-nagy** 2016-04-18 16:17 UTC
