### ISSUE TITLE
Inline Editing cells with validation

### ISSUE THREAD

**Issue by bastienJS** [daniel-nagy/md-data-table#10] opened 2015-06-10 14:43 UTC
I request for inline editing cells with validation done the material design way integrated into your demo:

http://codepen.io/anon/pen/zGzrgy

Thanks :-)

**Comment by daniel-nagy** [comment] 2015-06-10 17:35
Duplicate of #7

I'm not sure what you mean by "the material design way" The link you provided doesn't support inline editing of cells (unless I'm missing something). Take a look at [table interaction](http://www.google.com/design/spec/components/data-tables.html#data-tables-interaction) as defined by the specification. Scroll down until you see editing dialogs. That would be the feature I would implement. 

Issue #7 is not currently at the top of my priority list. I want to first make sure the general usability and experience is acceptable so people who need tables in there application now have something to work with.

If you have any further thoughts on how editing dialogs should be implemented or what features they should support please let me know. :smiley:

**Closed by daniel-nagy** 2015-06-10 17:36 UTC

**Comment by bastienJS** [comment] 2015-06-11 12:56
Hey Daniel,

of course the link does not provide inline editing. This is what I asked for :D  Sure I can do contenteditable="true" on the td-tag but I have no idea how to make it feel and look according material design and I am sure you might know it :-)
