### ISSUE TITLE
Row issue

### ISSUE THREAD

**Issue by Synturas** [daniel-nagy/md-data-table#91] opened 2015-08-17 11:06 UTC
There seems to be an issue with selecting the rows in this order (not only in ie): 

![image](https://cloud.githubusercontent.com/assets/8062692/9303721/c246ffe0-44e0-11e5-8fca-54c260482bfb.png)

**Comment by daniel-nagy** [comment] 2015-08-17 11:34
What order are you selecting them in? What version of Angular are you using? Checkbox selection is known to be broken in Angular 1.4.4

**Comment by Synturas** [comment] 2015-08-17 12:30
The order is shown by the numbers in the picture below, notice that 1 doesn't click the select box, it hits the row, where 2 hits the select box.

**Comment by daniel-nagy** [comment] 2015-08-17 13:07
I was only able to reproduce this in Angular 1.4.4

**Comment by Synturas** [comment] 2015-08-17 14:48
Okay, then nvm maybe i have been incorrect with my previous version number.

**Comment by daniel-nagy** [comment] 2015-08-19 11:30
dupe of #84

**Closed by daniel-nagy** 2015-08-19 11:30 UTC
