### ISSUE TITLE
Column ordering not working for dynamically generated columns

### ISSUE THREAD

**Issue by nathanmarks** [daniel-nagy/md-data-table#18] opened 2015-06-22 15:31 UTC
When I have the`th` attribute set to `order-by="{{column.key}}"`, it causes the sorting function to attempt to sort by that string rather than the actual value bound to it. This is problematic for a table with dynamically generated columns, for eg:

```
<th
  ng-repeat="column in ::vm.config.columns"
  ng-attr-numeric="::column.type === 'numeric'"
  order-by="{{column.key}}"
>
  {{::column.heading}}
</th>
```

**Comment by daniel-nagy** [comment] 2015-06-22 16:11
The problem is I'm assigning the `ng-click` attribute before it is compiled [here](https://github.com/daniel-nagy/md-data-table/blob/951a6f284a5ef18be8f05c357eb9f5188aa28ac8/app/md-data-table/scripts/mdDataTableHeadDirective.js#L117). We'll most likely need to move this to the `postLink` function and compile it manually. I can take care of this after work today if you don't fix it first :smiley:.

**Comment by daniel-nagy** [comment] 2015-06-24 01:31
@nathanmarks please confirm that commit 141aa5d18ae5d7a55082b23f173af01e0c8dc04f has solved this issue.

**Comment by nathanmarks** [comment] 2015-06-24 14:58
@daniel-nagy Looks good! Thanks.

Another thing I noticed that I think would be useful (and allow for more flexibility for more features) is to have the column type set by an attribute value rather than just having the attribute "numeric" in the tag.

I'm having difficulties using this without ng-if which I really don't want to do.

**Comment by daniel-nagy** [comment] 2015-06-24 15:25
Okay that makes sense. I'm going to close this issue and open a new one.

**Closed by daniel-nagy** 2015-06-24 15:25 UTC
